In [2]:
import pandas as pd 
import numpy as np
data_path = '../input/'

In [3]:
train = pd.read_pickle(data_path+'/train.pkl')

In [4]:
def moving_average(a, n):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret / n

In [5]:
train['ma1'] = train.groupby('Asset_ID').Close.transform(lambda x: moving_average(x.values, 5))
train.head()

,timestamp,Asset_ID,Count,Open,High,Low,Close,Volume,VWAP,Target,ma1
0,1514764860,2,40.0,2376.5800,2399.5000,2357.1400,2374.5900,19.233005,2373.116392,-0.004218,474.91800
1,1514764860,0,5.0,8.5300,8.5300,8.5300,8.5300,78.380000,8.530000,-0.014399,1.70600
2,1514764860,1,229.0,13835.1940,14013.8000,13666.1100,13850.1760,31.550062,13827.062093,-0.014643,2770.03520
3,1514764860,5,32.0,7.6596,7.6596,7.6567,7.6576,6626.713370,7.657713,-0.013922,1.53152
4,1514764860,7,5.0,25.9200,25.9200,25.8740,25.8770,121.087310,25.891363,-0.008264,5.17540

In [6]:
for i in train.Asset_ID.unique():
    train.loc[train.Asset_ID==i, 'ma2'] = moving_average(train[train.Asset_ID==i].Close.values, 5)

In [7]:
train.head()

,timestamp,Asset_ID,Count,Open,High,Low,Close,Volume,VWAP,Target,ma1,ma2
0,1514764860,2,40.0,2376.5800,2399.5000,2357.1400,2374.5900,19.233005,2373.116392,-0.004218,474.91800,474.91800
1,1514764860,0,5.0,8.5300,8.5300,8.5300,8.5300,78.380000,8.530000,-0.014399,1.70600,1.70600
2,1514764860,1,229.0,13835.1940,14013.8000,13666.1100,13850.1760,31.550062,13827.062093,-0.014643,2770.03520,2770.03520
3,1514764860,5,32.0,7.6596,7.6596,7.6567,7.6576,6626.713370,7.657713,-0.013922,1.53152,1.53152
4,1514764860,7,5.0,25.9200,25.9200,25.8740,25.8770,121.087310,25.891363,-0.008264,5.17540,5.17540

In [8]:
train['ln_Close'] = np.log(train['Close'])
train['log_return_5'] = train['ln_Close'] - train.groupby('Asset_ID')['ln_Close'].shift(5)
train.head(50)

,timestamp,Asset_ID,Count,Open,High,Low,Close,Volume,VWAP,Target,ma1,ma2,ln_Close,log_return_5
0,1514764860,2,40.0,2376.580000,2399.5000,2357.1400,2374.590000,19.233005,2373.116392,-0.004218,474.918000,474.918000,7.772580,NaN
1,1514764860,0,5.0,8.530000,8.5300,8.5300,8.530000,78.380000,8.530000,-0.014399,1.706000,1.706000,2.143589,NaN
2,1514764860,1,229.0,13835.194000,14013.8000,13666.1100,13850.176000,31.550062,13827.062093,-0.014643,2770.035200,2770.035200,9.536053,NaN
3,1514764860,5,32.0,7.659600,7.6596,7.6567,7.657600,6626.713370,7.657713,-0.013922,1.531520,1.531520,2.035699,NaN
4,1514764860,7,5.0,25.920000,25.9200,25.8740,25.877000,121.087310,25.891363,-0.008264,5.175400,5.175400,3.253355,NaN
5,1514764860,6,173.0,738.302500,746.0000,732.5100,738.507500,335.987856,738.839291,-0.004809,147.701500,147.701500,6.604631,NaN
6,1514764860,9,167.0,225.330000,227.7800,222.9800,225.206667,411.896642,225.197944,-0.009791,45.041333,45.041333,5.417018,NaN
7,1514764860,11,7.0,329.090000,329.8800,329.0900,329.460000,6.635710,329.454118,NaN,65.892000,65.892000,5.797455,NaN
8,1514764920,2,53.0,2374.553333,2400.9000,2354.2000,2372.286667,24.050259,2371.434498,-0.004079,949.375333,949.375333,7.771610,NaN
9,1514764920,0,7.0,8.530000,8.5300,8.5145,8.514500,71.390000,8.520215,-0.015875,3.408900,3.408900,2.141771,NaN
10,1514764920,1,235.0,13835.036000,14052.3000,13680.0000,13828.102000,31.046432,13840.362591,-0.015037,5535.655600,5535.655600,9.534458,NaN
11,1514764920,5,10.0,7.656800,7.6569,7.6567,7.656700,3277.475494,7.656749,-0.014534,3.062860,3.062860,2.035581,NaN
12,1514764920,7,1.0,25.897000,25.8970,25.8970,25.897000,1.468019,25.897000,-0.029902,10.354800,10.354800,3.254127,NaN
13,1514764920,6,192.0,738.507500,745.1400,732.4900,738.260000,232.793141,738.268967,-0.004441,295.353500,295.353500,6.604296,NaN
14,1514764920,9,212.0,225.133333,227.3800,222.4500,224.856667,3640.502706,224.446625,-0.012991,90.012667,90.012667,5.415463,NaN
15,1514764920,11,1.0,329.450000,329.4500,329.4500,329.450000,0.349420,329.450000,-0.009690,131.782000,131.782000,5.797425,NaN
16,1514764980,2,61.0,2371.633333,2401.9000,2353.7000,2372.063333,42.676438,2375.442755,-0.002892,1423.788000,1423.788000,7.771515,NaN
17,1514764980,0,45.0,8.506500,8.5299,8.4848,8.484800,1546.820000,8.501394,-0.015410,5.105860,5.105860,2.138276,NaN
18,1514764980,1,528.0,13823.900000,14000.4000,13601.0000,13801.314000,55.061820,13806.068014,-0.010309,8295.918400,8295.918400,9.532519,NaN
19,1514764980,5,22.0,7.656900,7.6569,7.6500,7.651200,5623.557585,7.654267,-0.012546,4.593100,4.593100,2.034862,NaN
20,1514764980,7,11.0,26.469500,27.0720,25.8690,26.469500,76.163922,26.469513,-0.030832,15.648700,15.648700,3.275993,NaN
21,1514764980,6,120.0,738.332500,745.1200,730.0000,737.502500,174.138031,737.994457,-0.004206,442.854000,442.854000,6.603269,NaN
22,1514764980,9,102.0,226.262000,229.1600,222.4400,226.000000,328.350286,225.980433,-0.003572,135.212667,135.212667,5.420535,NaN
23,1514764980,11,3.0,329.270000,329.2700,329.1900,329.190000,1.189553,329.198979,0.006567,197.620000,197.620000,5.796635,NaN
24,1514765040,2,95.0,2376.060000,2406.4000,2344.0000,2370.566667,37.820918,2371.096152,-0.003718,1897.901333,1897.901333,7.770884,NaN
25,1514765040,0,14.0,8.500900,8.5066,8.4744,8.500900,125.800000,8.479810,-0.012524,6.806040,6.806040,2.140172,NaN
26,1514765040,1,435.0,13802.512000,13999.0000,13576.2800,13768.040000,38.780529,13783.598101,-0.008999,11049.526400,11049.526400,9.530105,NaN
27,1514765040,5,12.0,7.650000,7.6503,7.6358,7.635800,1696.632459,7.649660,-0.011170,6.120260,6.120260,2.032848,NaN
28,1514765040,7,16.0,26.459000,27.0700,25.8290,26.449500,408.774848,26.456735,-0.028899,20.938600,20.938600,3.275237,NaN
29,1514765040,6,156.0,737.222500,744.6900,728.9300,737.102500,165.383926,737.303631,-0.002205,590.274500,590.274500,6.602727,NaN
30,1514765040,9,138.0,225.080000,226.7200,221.0000,224.275000,507.405579,224.552341,-0.002556,180.067667,180.067667,5.412873,NaN
31,1514765040,11,2.0,328.160000,328.1600,328.1600,328.160000,1.512079,328.160000,-0.007299,263.252000,263.252000,5.793501,NaN
32,1514765100,2,33.0,2372.656667,2404.6000,2343.4000,2370.173333,8.519679,2370.345730,-0.002171,2371.936000,2371.936000,7.770718,NaN
33,1514765100,0,5.0,8.500700,8.5007,8.4560,8.456000,125.010000,8.458435,-0.005940,8.497240,8.497240,2.134876,NaN
34,1514765100,1,742.0,13766.000000,13955.9000,13554.4400,13724.914000,108.501637,13735.586842,-0.008079,13794.509200,13794.509200,9.526968,NaN
35,1514765100,5,19.0,7.635800,7.6358,7.6100,7.610000,2268.362218,7.628076,-0.006154,7.642260,7.642260,2.029463,NaN
36,1514765100,7,25.0,26.451500,27.0700,25.7830,26.437000,529.337600,26.442988,-0.030909,26.226000,26.226000,3.274765,NaN
37,1514765100,6,118.0,736.530000,743.8000,727.1100,735.705000,193.078039,736.163026,-0.001744,737.415500,737.415500,6.600829,NaN
38,1514765100,9,204.0,224.507500,225.9600,221.2500,223.820000,1035.671830,224.032953,0.000531,224.831667,224.831667,5.410842,NaN
39,1514765100,11,7.0,328.180000,328.1800,327.4300,327.430000,11.997972,328.077776,-0.010619,328.738000,328.738000,5.791274,NaN
40,1514765160,2,44.0,2368.806667,2400.1000,2344.0000,2367.486667,27.459795,2367.328281,-0.009202,2370.515333,2370.515333,7.769584,-0.002996
41,1514765160,0,89.0,8.456000,8.4560,8.3999,8.400000,3765.250000,8.403468,-0.005455,8.471240,8.471240,2.128232,-0.015358
42,1514765160,1,554.0,13717.714000,14000.7000,13520.0000,13717.112000,70.805776,13706.952030,-0.004422,13767.896400,13767.896400,9.526399,-0.009654
43,1514765160,5,53.0,7.619200,7.6192,7.5359,7.572000,4079.555978,7.581642,-0.008654,7.625140,7.625140,2.024457,-0.011241
44,1514765160,7,76.0,26.425500,27.0730,25.5500,26.400000,1857.936529,26.352542,NaN,26.330600,26.330600,3.273364,0.020009
45,1514765160,6,119.0,735.842500,743.8000,725.0000,735.200000,366.585886,734.816231,-0.001331,736.754000,736.754000,6.600143,-0.004489
46,1514765160,9,135.0,223.787500,225.5900,220.0400,223.127500,873.793342,223.541700,-0.002572,224.415833,224.415833,5.407743,-0.009275
47,1514765160,11,9.0,332.000000,336.5600,327.1000,331.940000,2.291827,331.898785,0.005323,329.234000,329.234000,5.804954,0.007499
48,1514765220,2,29.0,2367.920000,2399.8000,2343.0000,2366.860000,57.679405,2366.808135,-0.004458,2369.430000,2369.430000,7.769319,-0.002290
49,1514765220,0,20.0,8.400000,8.4000,8.3800,8.395800,827.170000,8.390564,-0.000644,8.447500,8.447500,2.127732,-0.014039

In [9]:
for i in train.Asset_ID.unique():
    train.loc[train.Asset_ID==i, 'log_return_5_'] = train[train.Asset_ID==i].ln_Close - train[train.Asset_ID==i].ln_Close.shift(5)

In [10]:
train.head(50)

,timestamp,Asset_ID,Count,Open,High,Low,Close,Volume,VWAP,Target,ma1,ma2,ln_Close,log_return_5,log_return_5_
0,1514764860,2,40.0,2376.580000,2399.5000,2357.1400,2374.590000,19.233005,2373.116392,-0.004218,474.918000,474.918000,7.772580,NaN,NaN
1,1514764860,0,5.0,8.530000,8.5300,8.5300,8.530000,78.380000,8.530000,-0.014399,1.706000,1.706000,2.143589,NaN,NaN
2,1514764860,1,229.0,13835.194000,14013.8000,13666.1100,13850.176000,31.550062,13827.062093,-0.014643,2770.035200,2770.035200,9.536053,NaN,NaN
3,1514764860,5,32.0,7.659600,7.6596,7.6567,7.657600,6626.713370,7.657713,-0.013922,1.531520,1.531520,2.035699,NaN,NaN
4,1514764860,7,5.0,25.920000,25.9200,25.8740,25.877000,121.087310,25.891363,-0.008264,5.175400,5.175400,3.253355,NaN,NaN
5,1514764860,6,173.0,738.302500,746.0000,732.5100,738.507500,335.987856,738.839291,-0.004809,147.701500,147.701500,6.604631,NaN,NaN
6,1514764860,9,167.0,225.330000,227.7800,222.9800,225.206667,411.896642,225.197944,-0.009791,45.041333,45.041333,5.417018,NaN,NaN
7,1514764860,11,7.0,329.090000,329.8800,329.0900,329.460000,6.635710,329.454118,NaN,65.892000,65.892000,5.797455,NaN,NaN
8,1514764920,2,53.0,2374.553333,2400.9000,2354.2000,2372.286667,24.050259,2371.434498,-0.004079,949.375333,949.375333,7.771610,NaN,NaN
9,1514764920,0,7.0,8.530000,8.5300,8.5145,8.514500,71.390000,8.520215,-0.015875,3.408900,3.408900,2.141771,NaN,NaN
10,1514764920,1,235.0,13835.036000,14052.3000,13680.0000,13828.102000,31.046432,13840.362591,-0.015037,5535.655600,5535.655600,9.534458,NaN,NaN
11,1514764920,5,10.0,7.656800,7.6569,7.6567,7.656700,3277.475494,7.656749,-0.014534,3.062860,3.062860,2.035581,NaN,NaN
12,1514764920,7,1.0,25.897000,25.8970,25.8970,25.897000,1.468019,25.897000,-0.029902,10.354800,10.354800,3.254127,NaN,NaN
13,1514764920,6,192.0,738.507500,745.1400,732.4900,738.260000,232.793141,738.268967,-0.004441,295.353500,295.353500,6.604296,NaN,NaN
14,1514764920,9,212.0,225.133333,227.3800,222.4500,224.856667,3640.502706,224.446625,-0.012991,90.012667,90.012667,5.415463,NaN,NaN
15,1514764920,11,1.0,329.450000,329.4500,329.4500,329.450000,0.349420,329.450000,-0.009690,131.782000,131.782000,5.797425,NaN,NaN
16,1514764980,2,61.0,2371.633333,2401.9000,2353.7000,2372.063333,42.676438,2375.442755,-0.002892,1423.788000,1423.788000,7.771515,NaN,NaN
17,1514764980,0,45.0,8.506500,8.5299,8.4848,8.484800,1546.820000,8.501394,-0.015410,5.105860,5.105860,2.138276,NaN,NaN
18,1514764980,1,528.0,13823.900000,14000.4000,13601.0000,13801.314000,55.061820,13806.068014,-0.010309,8295.918400,8295.918400,9.532519,NaN,NaN
19,1514764980,5,22.0,7.656900,7.6569,7.6500,7.651200,5623.557585,7.654267,-0.012546,4.593100,4.593100,2.034862,NaN,NaN
20,1514764980,7,11.0,26.469500,27.0720,25.8690,26.469500,76.163922,26.469513,-0.030832,15.648700,15.648700,3.275993,NaN,NaN
21,1514764980,6,120.0,738.332500,745.1200,730.0000,737.502500,174.138031,737.994457,-0.004206,442.854000,442.854000,6.603269,NaN,NaN
22,1514764980,9,102.0,226.262000,229.1600,222.4400,226.000000,328.350286,225.980433,-0.003572,135.212667,135.212667,5.420535,NaN,NaN
23,1514764980,11,3.0,329.270000,329.2700,329.1900,329.190000,1.189553,329.198979,0.006567,197.620000,197.620000,5.796635,NaN,NaN
24,1514765040,2,95.0,2376.060000,2406.4000,2344.0000,2370.566667,37.820918,2371.096152,-0.003718,1897.901333,1897.901333,7.770884,NaN,NaN
25,1514765040,0,14.0,8.500900,8.5066,8.4744,8.500900,125.800000,8.479810,-0.012524,6.806040,6.806040,2.140172,NaN,NaN
26,1514765040,1,435.0,13802.512000,13999.0000,13576.2800,13768.040000,38.780529,13783.598101,-0.008999,11049.526400,11049.526400,9.530105,NaN,NaN
27,1514765040,5,12.0,7.650000,7.6503,7.6358,7.635800,1696.632459,7.649660,-0.011170,6.120260,6.120260,2.032848,NaN,NaN
28,1514765040,7,16.0,26.459000,27.0700,25.8290,26.449500,408.774848,26.456735,-0.028899,20.938600,20.938600,3.275237,NaN,NaN
29,1514765040,6,156.0,737.222500,744.6900,728.9300,737.102500,165.383926,737.303631,-0.002205,590.274500,590.274500,6.602727,NaN,NaN
30,1514765040,9,138.0,225.080000,226.7200,221.0000,224.275000,507.405579,224.552341,-0.002556,180.067667,180.067667,5.412873,NaN,NaN
31,1514765040,11,2.0,328.160000,328.1600,328.1600,328.160000,1.512079,328.160000,-0.007299,263.252000,263.252000,5.793501,NaN,NaN
32,1514765100,2,33.0,2372.656667,2404.6000,2343.4000,2370.173333,8.519679,2370.345730,-0.002171,2371.936000,2371.936000,7.770718,NaN,NaN
33,1514765100,0,5.0,8.500700,8.5007,8.4560,8.456000,125.010000,8.458435,-0.005940,8.497240,8.497240,2.134876,NaN,NaN
34,1514765100,1,742.0,13766.000000,13955.9000,13554.4400,13724.914000,108.501637,13735.586842,-0.008079,13794.509200,13794.509200,9.526968,NaN,NaN
35,1514765100,5,19.0,7.635800,7.6358,7.6100,7.610000,2268.362218,7.628076,-0.006154,7.642260,7.642260,2.029463,NaN,NaN
36,1514765100,7,25.0,26.451500,27.0700,25.7830,26.437000,529.337600,26.442988,-0.030909,26.226000,26.226000,3.274765,NaN,NaN
37,1514765100,6,118.0,736.530000,743.8000,727.1100,735.705000,193.078039,736.163026,-0.001744,737.415500,737.415500,6.600829,NaN,NaN
38,1514765100,9,204.0,224.507500,225.9600,221.2500,223.820000,1035.671830,224.032953,0.000531,224.831667,224.831667,5.410842,NaN,NaN
39,1514765100,11,7.0,328.180000,328.1800,327.4300,327.430000,11.997972,328.077776,-0.010619,328.738000,328.738000,5.791274,NaN,NaN
40,1514765160,2,44.0,2368.806667,2400.1000,2344.0000,2367.486667,27.459795,2367.328281,-0.009202,2370.515333,2370.515333,7.769584,-0.002996,-0.002996
41,1514765160,0,89.0,8.456000,8.4560,8.3999,8.400000,3765.250000,8.403468,-0.005455,8.471240,8.471240,2.128232,-0.015358,-0.015358
42,1514765160,1,554.0,13717.714000,14000.7000,13520.0000,13717.112000,70.805776,13706.952030,-0.004422,13767.896400,13767.896400,9.526399,-0.009654,-0.009654
43,1514765160,5,53.0,7.619200,7.6192,7.5359,7.572000,4079.555978,7.581642,-0.008654,7.625140,7.625140,2.024457,-0.011241,-0.011241
44,1514765160,7,76.0,26.425500,27.0730,25.5500,26.400000,1857.936529,26.352542,NaN,26.330600,26.330600,3.273364,0.020009,0.020009
45,1514765160,6,119.0,735.842500,743.8000,725.0000,735.200000,366.585886,734.816231,-0.001331,736.754000,736.754000,6.600143,-0.004489,-0.004489
46,1514765160,9,135.0,223.787500,225.5900,220.0400,223.127500,873.793342,223.541700,-0.002572,224.415833,224.415833,5.407743,-0.009275,-0.009275
47,1514765160,11,9.0,332.000000,336.5600,327.1000,331.940000,2.291827,331.898785,0.005323,329.234000,329.234000,5.804954,0.007499,0.007499
48,1514765220,2,29.0,2367.920000,2399.8000,2343.0000,2366.860000,57.679405,2366.808135,-0.004458,2369.430000,2369.430000,7.769319,-0.002290,-0.002290
49,1514765220,0,20.0,8.400000,8.4000,8.3800,8.395800,827.170000,8.390564,-0.000644,8.447500,8.447500,2.127732,-0.014039,-0.014039

In [11]:
def reduce_mem_usage(df, verbose=True):
    numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
    start_mem = df.memory_usage().sum() / 1024**2 
    dfs = []
    for col in df.columns:
        col_type = df[col].dtypes
        if col_type in numerics:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    dfs.append(df[col].astype(np.int8))
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    dfs.append(df[col].astype(np.int16))
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    dfs.append(df[col].astype(np.int32))
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    dfs.append(df[col].astype(np.int64) ) 
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    dfs.append(df[col].astype(np.float16))
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    dfs.append(df[col].astype(np.float32))
                else:
                    dfs.append(df[col].astype(np.float64))
        else:
            dfs.append(df[col])
    
    df_out = pd.concat(dfs, axis=1)
    if verbose:
        end_mem = df_out.memory_usage().sum() / 1024**2
        num_reduction = str(100 * (start_mem - end_mem) / start_mem)
        print(f'Mem. usage decreased to {str(end_mem)[:3]}Mb:  {num_reduction[:2]}% reduction')
    return df_out

In [12]:
reduce_mem_usage(train)

Mem. usage decreased to 947Mb:  65% reduction

,timestamp,Asset_ID,Count,Open,High,Low,Close,Volume,VWAP,Target,ma1,ma2,ln_Close,log_return_5,log_return_5_
0,1514764860,2,40.0,2376.000000,2400.000000,2358.000000,2374.000000,1.923301e+01,2373.116392,-0.004219,475.000000,475.000000,7.773438,NaN,NaN
1,1514764860,0,5.0,8.531250,8.531250,8.531250,8.531250,7.838000e+01,8.530000,-0.014397,1.706055,1.706055,2.144531,NaN,NaN
2,1514764860,1,229.0,13832.000000,14016.000000,13664.000000,13848.000000,3.155006e+01,13827.062093,-0.014641,2770.000000,2770.000000,9.539062,NaN,NaN
3,1514764860,5,32.0,7.660156,7.660156,7.656250,7.656250,6.626713e+03,7.657713,-0.013924,1.531250,1.531250,2.035156,NaN,NaN
4,1514764860,7,5.0,25.921875,25.921875,25.875000,25.875000,1.210873e+02,25.891363,-0.008263,5.175781,5.175781,3.253906,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24236801,1632182400,9,775.0,157.125000,157.250000,156.750000,157.000000,4.663726e+03,156.994319,NaN,156.750000,156.750000,5.054688,-0.003281,-0.003281
24236802,1632182400,10,34.0,2438.000000,2438.000000,2430.000000,2432.000000,3.975460e+00,2434.818747,NaN,2426.000000,2426.000000,7.796875,-0.000728,-0.000728
24236803,1632182400,13,380.0,0.091370,0.091553,0.091248,0.091370,2.193732e+06,0.091388,NaN,0.091125,0.091125,-2.392578,-0.001359,-0.001359
24236804,1632182400,12,177.0,0.282227,0.282471,0.281738,0.281982,1.828508e+05,0.282134,NaN,0.281494,0.281494,-1.265625,-0.002367,-0.002367
24236805,1632182400,11,48.0,232.750000,232.750000,232.250000,232.250000,1.035123e+02,232.569697,NaN,231.750000,231.750000,5.449219,-0.001538,-0.001538